{
 "title": "Statistique pour Flechette",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "player", "label": "Joueurs", "query": "SELECT username FROM player" }
  ]
 },
 "panels": [
  {
   "title": "Heatmap des tirs",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 30, "w": 12, "x": 0, "y": 0 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "first",
      "firstNotNull",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "rawSql": "SELECT di.input, count(*) as valeur\nFROM dart_input di\nINNER JOIN player p ON di.id_player = p.id_player\nINNER JOIN game g ON g.id_game = di.id_game\nINNER JOIN game_type gt ON g.id_game_type = gt.id_game_type\nWHERE p.username = \"$player\" \nAND g.active = false\nAND gt.label NOT LIKE \"%TRAINING%\"\nGROUP BY input\norder by score;"
    }
   ]
  },
  {
   "title": "Taux de victoire",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "step" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total, p.username as Joueur\nFROM game g \nLEFT JOIN player p ON g.id_player_win = p.id_player\nINNER JOIN game_type gt ON g.id_game_type = gt.id_game_type\n\nWHERE g.active = 0 AND gt.label NOT LIKE \"%TRAINING%\" GROUP BY id_player_win;"
    }
   ]
  },
  {
   "title": "Général",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT p.username,\r\nCOUNT(distinct di.id_dart_input) as result,\r\n(SELECT COUNT(*) AS counter FROM dart_input di INNER JOIN game g ON g.id_game = di.id_game INNER JOIN game_type gt ON gt.id_game_type = g.id_game_type WHERE p.id_player = di.id_player AND input LIKE \"SBULL\" AND g.active = false AND gt.label NOT LIKE \"%TRAINING%\") AS DEMIBULL,\r\n(SELECT COUNT(*) AS counter FROM dart_input di INNER JOIN game g ON g.id_game = di.id_game INNER JOIN game_type gt ON gt.id_game_type = g.id_game_type WHERE p.id_player = di.id_player AND input LIKE \"DBULL\" AND g.active = FALSE AND gt.label NOT LIKE \"%TRAINING%\") AS BULL,\r\n(SELECT COUNT(*) AS counter FROM dart_input di INNER JOIN game g ON g.id_game = di.id_game INNER JOIN game_type gt ON gt.id_game_type = g.id_game_type WHERE p.id_player = di.id_player AND input LIKE \"T20\" AND g.active = FALSE AND gt.label NOT LIKE \"%TRAINING%\") AS T20\r\nFROM  player p \r\nLEFT JOIN dart_input di \r\nON di.id_player = p.id_player\r\nINNER JOIN game g ON di.id_game = g.id_game\r\nINNER JOIN game_type gt ON gt.id_game_type = g.id_game_type\r\nWHERE gt.label NOT LIKE \"%TRAINING%\"\r\nGROUP BY p.username;"
    }
   ]
  },
  {
   "title": "Moyenne - 10 parties",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT g.game_name, AVG(score) as Moyenne FROM dart_input di \r\nINNER JOIN player p ON di.id_player = p.id_player \r\nINNER JOIN game g ON g.id_game = di.id_game\r\nINNER JOIN game_type gt\r\n\tON gt.id_game_type = g.id_game_type\r\nWHERE p.username LIKE \"$player\"\r\nAND g.active = false\r\nAND gt.label NOT LIKE \"%TRAINING%\"\r\nGROUP BY di.id_game\r\nORDER BY di.id_game DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Moyenne générale",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(score) as value FROM dart_input di\r\nINNER JOIN game g\r\n\tON g.id_game = di.id_game\r\nINNER JOIN game_type gt\r\n\tON gt.id_game_type = g.id_game_type\r\nINNER JOIN player p\r\n\tON p.id_player = di.id_player\r\nWHERE gt.label NOT LIKE \"%TRAINING%\"\r\nAND p.username LIKE \"$player\"\r\nAND g.active = FALSE\r\nGROUP BY g.id_game\r\nORDER BY g.id_game DESC"
    }
   ]
  },
  {
   "title": "Moyenne générale - 5 parties",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(score) as value FROM dart_input di\r\nINNER JOIN game g\r\n\tON g.id_game = di.id_game\r\nINNER JOIN game_type gt\r\n\tON gt.id_game_type = g.id_game_type\r\nINNER JOIN player p\r\n\tON p.id_player = di.id_player\r\nWHERE gt.label NOT LIKE \"%TRAINING%\"\r\nAND p.username LIKE \"$player\"\r\nAND g.active = FALSE\r\nGROUP BY g.id_game\r\nORDER BY g.id_game DESC LIMIT 5"
    }
   ]
  },
  {
   "title": "Moyenne générale - 10 parties",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(score) as value FROM dart_input di\r\nINNER JOIN game g\r\n\tON g.id_game = di.id_game\r\nINNER JOIN game_type gt\r\n\tON gt.id_game_type = g.id_game_type\r\nINNER JOIN player p\r\n\tON p.id_player = di.id_player\r\nWHERE gt.label NOT LIKE \"%TRAINING%\"\r\nAND p.username LIKE \"$player\"\r\nAND g.active = FALSE\r\nGROUP BY g.id_game\r\nORDER BY g.id_game DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Taux de touche par case",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT di.input, count(*) as valeur\nFROM dart_input di\nINNER JOIN player p ON di.id_player = p.id_player\nINNER JOIN game g ON g.id_game = di.id_game\nINNER JOIN game_type gt ON g.id_game_type = gt.id_game_type\nWHERE p.username = \"$player\" \nAND g.active = false\nAND gt.label NOT LIKE \"%TRAINING%\"\nGROUP BY input\norder by score;"
    }
   ]
  },
  {
   "title": "Flechettes",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT @id:= @id - 1 id, dires.score as value \r\nFROM (\r\nSELECT di.score, di.id_dart_input FROM dart_input di\r\nINNER JOIN player p ON di.id_player = p.id_player\r\nINNER JOIN game g ON  g.id_game = di.id_game\r\nINNER JOIN game_type gt ON g.id_game_type = gt.id_game_type\r\nWHERE p.username LIKE \"$player\" \r\nAND gt.label NOT LIKE \"%TRAINING%\"\r\nAND g.active = 0\r\nORDER BY di.id_dart_input DESC LIMIT 100\r\n) dires, (SELECT @id := 100) m ;\r\n\r\n\r\n"
    }
   ]
  }
 ]
}